BEGIN TRANSACTION
BEGIN TRY
;WITH STOREUPDATE AS(
SELECT
      New.Id
	, OUTL_OUTLET
	, OUTL_PRICE_ZONE
	, OUTL_COST_ZONE 
	, (SELECT Id FROM CostPriceZones WHERE [TYPE] = 1 AND  Code=OUTL_COST_ZONE) CostZoneId_1
	, (SELECT Id FROM CostPriceZones WHERE [TYPE] = 2 AND  Code=OUTL_PRICE_ZONE) PriceZoneId_1
	, CostZoneId
	, PriceZoneId
FROM
[DBS99.COYOTEPOS.COM.AU].[AASandBox].[dbo].OUTLTBL OLD
INNER JOIN Store New ON old.OUTL_OUTLET=New.Code
)
--SELECT * FROM STOREUPDATE
UPDATE STOREUPDATE SET CostZoneId=CostZoneId_1,PriceZoneId=PriceZoneId_1

COMMIT TRANSACTION
END TRY

BEGIN CATCH
	SELECT ERROR_NUMBER() AS ErrorNumber
		,ERROR_SEVERITY() AS ErrorSeverity
		,ERROR_STATE() AS ErrorState
		,ERROR_PROCEDURE() AS ErrorProcedure
		,ERROR_LINE() AS ErrorLine
		,ERROR_MESSAGE() AS ErrorMessage;
		
	ROLLBACK TRANSACTION
END CATCH

SELECT * FROm STORE