BEGIN TRANSACTION 
BEGIN TRY

--DBCC CHECKIDENT('Keypad', RESEED,0)
--SELECT * FROm Keypad
--DELETE FROM Keypad
INSERT INTO Keypad 
(
	  OutletId
	, Code
	, [Desc]
	, Status
	, CreatedAt
	, UpdatedAt
	, CreatedById
	, UpdatedById
	, IsDeleted
	, KeyPadButtonJSONData
)
SELECT 
	  new.Id OutletId
	, CODE_KEY_ALP Code
	, LEFT(RTRIM(CODE_DESC),30) [Desc]
	, 1 [Status]
	, CASE WHEN CODE_TIMESTAMP IS NULL THEN GETUTCDATE() ELSE  CODE_TIMESTAMP END C 
	, CASE WHEN CODE_TIMESTAMP IS NULL THEN GETUTCDATE() ELSE  CODE_TIMESTAMP END  U
	, 1 CreatedBy
	, 1 UpdatedBy
	, 0 IsDeleted
	, NULL KeyPadButtonJSONData
FROM [DBS99.COYOTEPOS.COM.AU].[AASandBox].[dbo].CODETBL old
INNER JOIN store new ON old.CODE_NUM_1=new.Code
WHERE CODE_KEY_Type ='KEYPAD'

COMMIT TRANSACTION
END TRY
BEGIN CATCH
   SELECT ERROR_NUMBER() AS ERRORNUMBER,ERROR_SEVERITY() AS ERRORSEVERITY,ERROR_STATE() AS ERRORSTATE,ERROR_PROCEDURE() AS ERRORPROCEDURE,
   ERROR_LINE() AS ERRORLINE,ERROR_MESSAGE() AS ERRORMESSAGE;
  ROLLBACK TRANSACTION
END CATCH 