BEGIN TRANSACTION 
BEGIN TRY

--DBCC CHECKIDENT('KeypadLevel', RESEED,0)
--DELETE FROM KeypadLevel

INSERT INTO KeypadLevel
(
 KeypadId
, [Desc]
, IsDeleted
, CreatedAt
, UpdatedAt
, CreatedById
, UpdatedById
)
SELECT 
	 new.ID
   , CODE_DESC
   , 0
   , CASE WHEN CODE_TIMESTAMP IS NULL THEN GETUTCDATE() ELSE  CODE_TIMESTAMP END C 
   , CASE WHEN CODE_TIMESTAMP IS NULL THEN GETUTCDATE() ELSE  CODE_TIMESTAMP END  U
   , 1
   , 1
FROM [DBS99.COYOTEPOS.COM.AU].[AASandBox].[dbo].CODETBL old
INNER JOIN Keypad new ON old.Code_key_alp=new.Code
WHERE CODE_KEY_Type ='KEYPAD_LEVS'
COMMIT TRANSACTION
END TRY
BEGIN CATCH
   SELECT ERROR_NUMBER() AS ERRORNUMBER,ERROR_SEVERITY() AS ERRORSEVERITY,ERROR_STATE() AS ERRORSTATE,ERROR_PROCEDURE() AS ERRORPROCEDURE,
   ERROR_LINE() AS ERRORLINE,ERROR_MESSAGE() AS ERRORMESSAGE;
  ROLLBACK TRANSACTION
END CATCH 