//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDIServiceReference
{
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://retailwebservicesv7.metcash.com")]
    public partial class Fault
    {
        
        private string codeField;
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Code
        {
            get
            {
                return this.codeField;
            }
            set
            {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Message
        {
            get
            {
                return this.messageField;
            }
            set
            {
                this.messageField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://xmlns.example.com/1428550316380", ConfigurationName="EDIServiceReference.RWSv7Services")]
    public interface RWSv7Services
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="/RetailWebServicesV7/InterfaceServices/RetailWebServicesV7Service.serviceagent/li" +
            "stDocumentsInternal", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(EDIServiceReference.Fault), Action="/RetailWebServicesV7/InterfaceServices/RetailWebServicesV7Service.serviceagent/li" +
            "stDocumentsInternal", Name="Fault", Namespace="http://retailwebservicesv7.metcash.com")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<EDIServiceReference.listDocumentsInternalResponse> listDocumentsInternalAsync(EDIServiceReference.listDocumentsInternalRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="/RetailWebServicesV7/InterfaceServices/RetailWebServicesV7Service.serviceagent/pl" +
            "aceOrder", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(EDIServiceReference.Fault), Action="/RetailWebServicesV7/InterfaceServices/RetailWebServicesV7Service.serviceagent/pl" +
            "aceOrder", Name="Fault", Namespace="http://retailwebservicesv7.metcash.com")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<EDIServiceReference.placeOrderResponse1> placeOrderAsync(EDIServiceReference.placeOrderRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="/RetailWebServicesV7/InterfaceServices/RetailWebServicesV7Service.serviceagent/ge" +
            "tOrderSummary", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(EDIServiceReference.Fault), Action="/RetailWebServicesV7/InterfaceServices/RetailWebServicesV7Service.serviceagent/ge" +
            "tOrderSummary", Name="Fault", Namespace="http://retailwebservicesv7.metcash.com")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<EDIServiceReference.getOrderSummaryResponse1> getOrderSummaryAsync(EDIServiceReference.getOrderSummaryRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="/RetailWebServicesV7/InterfaceServices/Service.serviceagent/RWSv7ServicesEndpoint" +
            "1/retrieveDocument", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(EDIServiceReference.Fault), Action="/RetailWebServicesV7/InterfaceServices/Service.serviceagent/RWSv7ServicesEndpoint" +
            "1/retrieveDocument", Name="Fault", Namespace="http://retailwebservicesv7.metcash.com")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<EDIServiceReference.retrieveDocumentResponse> retrieveDocumentAsync(EDIServiceReference.retrieveDocumentRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="/RetailWebServicesV7/InterfaceServices/Service.serviceagent/RWSv7ServicesEndpoint" +
            "1/listDocuments", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(EDIServiceReference.Fault), Action="/RetailWebServicesV7/InterfaceServices/Service.serviceagent/RWSv7ServicesEndpoint" +
            "1/listDocuments", Name="Fault", Namespace="http://retailwebservicesv7.metcash.com")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<EDIServiceReference.listDocumentsResponse> listDocumentsAsync(EDIServiceReference.listDocumentsInternalRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="/RetailWebServicesV7/InterfaceServices/RetailWebServicesV7Service.serviceagent/ge" +
            "tNextDocument", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(EDIServiceReference.Fault), Action="/RetailWebServicesV7/InterfaceServices/RetailWebServicesV7Service.serviceagent/ge" +
            "tNextDocument", Name="Fault", Namespace="http://retailwebservicesv7.metcash.com")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<EDIServiceReference.getNextDocumentResponse> getNextDocumentAsync(EDIServiceReference.getNextDocumentRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://retailwebservicesv7.metcash.com")]
    public partial class OperatingSystem
    {
        
        private string systemNameField;
        
        private string systemTypeField;
        
        private string servicePackField;
        
        private string versionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string SystemName
        {
            get
            {
                return this.systemNameField;
            }
            set
            {
                this.systemNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string SystemType
        {
            get
            {
                return this.systemTypeField;
            }
            set
            {
                this.systemTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string ServicePack
        {
            get
            {
                return this.servicePackField;
            }
            set
            {
                this.servicePackField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Version
        {
            get
            {
                return this.versionField;
            }
            set
            {
                this.versionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://retailwebservicesv7.metcash.com")]
    public partial class VendorDetails
    {
        
        private string vendorField;
        
        private string softwareField;
        
        private string versionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Vendor
        {
            get
            {
                return this.vendorField;
            }
            set
            {
                this.vendorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Software
        {
            get
            {
                return this.softwareField;
            }
            set
            {
                this.softwareField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Version
        {
            get
            {
                return this.versionField;
            }
            set
            {
                this.versionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://retailwebservicesv7.metcash.com")]
    public partial class Authentication
    {
        
        private string b2BAccountField;
        
        private string passwordField;
        
        private string securityTokenField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string B2BAccount
        {
            get
            {
                return this.b2BAccountField;
            }
            set
            {
                this.b2BAccountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Password
        {
            get
            {
                return this.passwordField;
            }
            set
            {
                this.passwordField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string SecurityToken
        {
            get
            {
                return this.securityTokenField;
            }
            set
            {
                this.securityTokenField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://retailwebservicesv7.metcash.com")]
    public partial class listDocumentsReq
    {
        
        private string customerIdField;
        
        private string stateCodeField;
        
        private string pillarIdField;
        
        private string documentTypeField;
        
        private string hostTypeField;
        
        private string dateFromField;
        
        private string dateToField;
        
        private bool listRetrievedFlagField;
        
        private bool listRetrievedFlagFieldSpecified;
        
        private DocumentReference documentReferenceField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string CustomerId
        {
            get
            {
                return this.customerIdField;
            }
            set
            {
                this.customerIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string StateCode
        {
            get
            {
                return this.stateCodeField;
            }
            set
            {
                this.stateCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string PillarId
        {
            get
            {
                return this.pillarIdField;
            }
            set
            {
                this.pillarIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string DocumentType
        {
            get
            {
                return this.documentTypeField;
            }
            set
            {
                this.documentTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string HostType
        {
            get
            {
                return this.hostTypeField;
            }
            set
            {
                this.hostTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string DateFrom
        {
            get
            {
                return this.dateFromField;
            }
            set
            {
                this.dateFromField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string DateTo
        {
            get
            {
                return this.dateToField;
            }
            set
            {
                this.dateToField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public bool ListRetrievedFlag
        {
            get
            {
                return this.listRetrievedFlagField;
            }
            set
            {
                this.listRetrievedFlagField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ListRetrievedFlagSpecified
        {
            get
            {
                return this.listRetrievedFlagFieldSpecified;
            }
            set
            {
                this.listRetrievedFlagFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public DocumentReference DocumentReference
        {
            get
            {
                return this.documentReferenceField;
            }
            set
            {
                this.documentReferenceField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://retailwebservicesv7.metcash.com")]
    public partial class DocumentReference
    {
        
        private string typeField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://retailwebservicesv7.metcash.com")]
    public partial class listAllDocsInternal
    {
        
        private string customerIdField;
        
        private string originalGUIDField;
        
        private string fileNameField;
        
        private string documentTypeField;
        
        private string hostTypeField;
        
        private string translatedGUIDField;
        
        private DocumentReference[] documentReferenceField;
        
        private System.DateTime docDateField;
        
        private bool docDateFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string CustomerId
        {
            get
            {
                return this.customerIdField;
            }
            set
            {
                this.customerIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string OriginalGUID
        {
            get
            {
                return this.originalGUIDField;
            }
            set
            {
                this.originalGUIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string FileName
        {
            get
            {
                return this.fileNameField;
            }
            set
            {
                this.fileNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string DocumentType
        {
            get
            {
                return this.documentTypeField;
            }
            set
            {
                this.documentTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string HostType
        {
            get
            {
                return this.hostTypeField;
            }
            set
            {
                this.hostTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string TranslatedGUID
        {
            get
            {
                return this.translatedGUIDField;
            }
            set
            {
                this.translatedGUIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("DocumentReference", Order=6)]
        public DocumentReference[] DocumentReference
        {
            get
            {
                return this.documentReferenceField;
            }
            set
            {
                this.documentReferenceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public System.DateTime DocDate
        {
            get
            {
                return this.docDateField;
            }
            set
            {
                this.docDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DocDateSpecified
        {
            get
            {
                return this.docDateFieldSpecified;
            }
            set
            {
                this.docDateFieldSpecified = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class listDocumentsInternalRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://retailwebservicesv7.metcash.com")]
        public EDIServiceReference.OperatingSystem OperatingSystem;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://retailwebservicesv7.metcash.com")]
        public EDIServiceReference.VendorDetails VendorDetails;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://retailwebservicesv7.metcash.com")]
        public EDIServiceReference.Authentication Authentication;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://retailwebservicesv7.metcash.com", Order=0)]
        public EDIServiceReference.listDocumentsReq listDocumentsReq;
        
        public listDocumentsInternalRequest()
        {
        }
        
        public listDocumentsInternalRequest(EDIServiceReference.OperatingSystem OperatingSystem, EDIServiceReference.VendorDetails VendorDetails, EDIServiceReference.Authentication Authentication, EDIServiceReference.listDocumentsReq listDocumentsReq)
        {
            this.OperatingSystem = OperatingSystem;
            this.VendorDetails = VendorDetails;
            this.Authentication = Authentication;
            this.listDocumentsReq = listDocumentsReq;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class listDocumentsInternalResponse
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://retailwebservicesv7.metcash.com")]
        public EDIServiceReference.Authentication Authentication;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://retailwebservicesv7.metcash.com", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("listAllDocsInternal", IsNullable=false)]
        public EDIServiceReference.listAllDocsInternal[] listDocumentsRespInternal;
        
        public listDocumentsInternalResponse()
        {
        }
        
        public listDocumentsInternalResponse(EDIServiceReference.Authentication Authentication, EDIServiceReference.listAllDocsInternal[] listDocumentsRespInternal)
        {
            this.Authentication = Authentication;
            this.listDocumentsRespInternal = listDocumentsRespInternal;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://retailwebservicesv7.metcash.com")]
    public partial class placeOrderRequest
    {
        
        private string customerIdField;
        
        private string stateCodeField;
        
        private string pillarIdField;
        
        private string orderTypeField;
        
        private string orderField;
        
        private string fileNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string CustomerId
        {
            get
            {
                return this.customerIdField;
            }
            set
            {
                this.customerIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string StateCode
        {
            get
            {
                return this.stateCodeField;
            }
            set
            {
                this.stateCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string PillarId
        {
            get
            {
                return this.pillarIdField;
            }
            set
            {
                this.pillarIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string OrderType
        {
            get
            {
                return this.orderTypeField;
            }
            set
            {
                this.orderTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Order
        {
            get
            {
                return this.orderField;
            }
            set
            {
                this.orderField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string fileName
        {
            get
            {
                return this.fileNameField;
            }
            set
            {
                this.fileNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://retailwebservicesv7.metcash.com")]
    public partial class placeOrderResponse
    {
        
        private OrderAck orderSummaryField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public OrderAck orderSummary
        {
            get
            {
                return this.orderSummaryField;
            }
            set
            {
                this.orderSummaryField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://retailwebservicesv7.metcash.com")]
    public partial class OrderAck
    {
        
        private string batchIdField;
        
        private string commentsField;
        
        private string timestampField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string batchId
        {
            get
            {
                return this.batchIdField;
            }
            set
            {
                this.batchIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string comments
        {
            get
            {
                return this.commentsField;
            }
            set
            {
                this.commentsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string timestamp
        {
            get
            {
                return this.timestampField;
            }
            set
            {
                this.timestampField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class placeOrderRequest1
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://retailwebservicesv7.metcash.com")]
        public EDIServiceReference.OperatingSystem OperatingSystem;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://retailwebservicesv7.metcash.com")]
        public EDIServiceReference.VendorDetails VendorDetails;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://retailwebservicesv7.metcash.com")]
        public EDIServiceReference.Authentication Authentication;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://retailwebservicesv7.metcash.com", Order=0)]
        public EDIServiceReference.placeOrderRequest placeOrderRequest;
        
        public placeOrderRequest1()
        {
        }
        
        public placeOrderRequest1(EDIServiceReference.OperatingSystem OperatingSystem, EDIServiceReference.VendorDetails VendorDetails, EDIServiceReference.Authentication Authentication, EDIServiceReference.placeOrderRequest placeOrderRequest)
        {
            this.OperatingSystem = OperatingSystem;
            this.VendorDetails = VendorDetails;
            this.Authentication = Authentication;
            this.placeOrderRequest = placeOrderRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class placeOrderResponse1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://retailwebservicesv7.metcash.com", Order=0)]
        public EDIServiceReference.placeOrderResponse placeOrderResponse;
        
        public placeOrderResponse1()
        {
        }
        
        public placeOrderResponse1(EDIServiceReference.placeOrderResponse placeOrderResponse)
        {
            this.placeOrderResponse = placeOrderResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://retailwebservicesv7.metcash.com")]
    public partial class getOrderSummaryRequest
    {
        
        private string customerIdField;
        
        private string stateCodeField;
        
        private string pillarIdField;
        
        private string batchIdField;
        
        private string timeStampField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string CustomerId
        {
            get
            {
                return this.customerIdField;
            }
            set
            {
                this.customerIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string StateCode
        {
            get
            {
                return this.stateCodeField;
            }
            set
            {
                this.stateCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string PillarId
        {
            get
            {
                return this.pillarIdField;
            }
            set
            {
                this.pillarIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string batchId
        {
            get
            {
                return this.batchIdField;
            }
            set
            {
                this.batchIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string timeStamp
        {
            get
            {
                return this.timeStampField;
            }
            set
            {
                this.timeStampField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://retailwebservicesv7.metcash.com")]
    public partial class getOrderSummaryResponse
    {
        
        private string responseField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string response
        {
            get
            {
                return this.responseField;
            }
            set
            {
                this.responseField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getOrderSummaryRequest1
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://retailwebservicesv7.metcash.com")]
        public EDIServiceReference.OperatingSystem OperatingSystem;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://retailwebservicesv7.metcash.com")]
        public EDIServiceReference.VendorDetails VendorDetails;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://retailwebservicesv7.metcash.com")]
        public EDIServiceReference.Authentication Authentication;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://retailwebservicesv7.metcash.com", Order=0)]
        public EDIServiceReference.getOrderSummaryRequest getOrderSummaryRequest;
        
        public getOrderSummaryRequest1()
        {
        }
        
        public getOrderSummaryRequest1(EDIServiceReference.OperatingSystem OperatingSystem, EDIServiceReference.VendorDetails VendorDetails, EDIServiceReference.Authentication Authentication, EDIServiceReference.getOrderSummaryRequest getOrderSummaryRequest)
        {
            this.OperatingSystem = OperatingSystem;
            this.VendorDetails = VendorDetails;
            this.Authentication = Authentication;
            this.getOrderSummaryRequest = getOrderSummaryRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getOrderSummaryResponse1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://retailwebservicesv7.metcash.com", Order=0)]
        public EDIServiceReference.getOrderSummaryResponse getOrderSummaryResponse;
        
        public getOrderSummaryResponse1()
        {
        }
        
        public getOrderSummaryResponse1(EDIServiceReference.getOrderSummaryResponse getOrderSummaryResponse)
        {
            this.getOrderSummaryResponse = getOrderSummaryResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://retailwebservicesv7.metcash.com")]
    public partial class retrieveDocumentReq
    {
        
        private string documentGUIDField;
        
        private string fileNameField;
        
        private bool zipFlagField;
        
        private bool zipFlagFieldSpecified;
        
        private string documentVersionField;
        
        private string transactionIdField;
        
        private bool flagAsCollectedField;
        
        private bool flagAsCollectedFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string DocumentGUID
        {
            get
            {
                return this.documentGUIDField;
            }
            set
            {
                this.documentGUIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string FileName
        {
            get
            {
                return this.fileNameField;
            }
            set
            {
                this.fileNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public bool ZipFlag
        {
            get
            {
                return this.zipFlagField;
            }
            set
            {
                this.zipFlagField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ZipFlagSpecified
        {
            get
            {
                return this.zipFlagFieldSpecified;
            }
            set
            {
                this.zipFlagFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string DocumentVersion
        {
            get
            {
                return this.documentVersionField;
            }
            set
            {
                this.documentVersionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string TransactionId
        {
            get
            {
                return this.transactionIdField;
            }
            set
            {
                this.transactionIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public bool FlagAsCollected
        {
            get
            {
                return this.flagAsCollectedField;
            }
            set
            {
                this.flagAsCollectedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool FlagAsCollectedSpecified
        {
            get
            {
                return this.flagAsCollectedFieldSpecified;
            }
            set
            {
                this.flagAsCollectedFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://retailwebservicesv7.metcash.com")]
    public partial class retrieveDocumentResp
    {
        
        private string documentGUIDField;
        
        private string payloadField;
        
        private bool zipFlagField;
        
        private string documentVersionField;
        
        private string digestField;
        
        private string documentSizeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string DocumentGUID
        {
            get
            {
                return this.documentGUIDField;
            }
            set
            {
                this.documentGUIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Payload
        {
            get
            {
                return this.payloadField;
            }
            set
            {
                this.payloadField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public bool ZipFlag
        {
            get
            {
                return this.zipFlagField;
            }
            set
            {
                this.zipFlagField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string DocumentVersion
        {
            get
            {
                return this.documentVersionField;
            }
            set
            {
                this.documentVersionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Digest
        {
            get
            {
                return this.digestField;
            }
            set
            {
                this.digestField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string DocumentSize
        {
            get
            {
                return this.documentSizeField;
            }
            set
            {
                this.documentSizeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class retrieveDocumentRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://retailwebservicesv7.metcash.com")]
        public EDIServiceReference.OperatingSystem OperatingSystem;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://retailwebservicesv7.metcash.com")]
        public EDIServiceReference.VendorDetails VendorDetails;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://retailwebservicesv7.metcash.com")]
        public EDIServiceReference.Authentication Authentication;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://retailwebservicesv7.metcash.com", Order=0)]
        public EDIServiceReference.retrieveDocumentReq retrieveDocumentReq;
        
        public retrieveDocumentRequest()
        {
        }
        
        public retrieveDocumentRequest(EDIServiceReference.OperatingSystem OperatingSystem, EDIServiceReference.VendorDetails VendorDetails, EDIServiceReference.Authentication Authentication, EDIServiceReference.retrieveDocumentReq retrieveDocumentReq)
        {
            this.OperatingSystem = OperatingSystem;
            this.VendorDetails = VendorDetails;
            this.Authentication = Authentication;
            this.retrieveDocumentReq = retrieveDocumentReq;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class retrieveDocumentResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://retailwebservicesv7.metcash.com", Order=0)]
        public EDIServiceReference.retrieveDocumentResp retrieveDocumentResp;
        
        public retrieveDocumentResponse()
        {
        }
        
        public retrieveDocumentResponse(EDIServiceReference.retrieveDocumentResp retrieveDocumentResp)
        {
            this.retrieveDocumentResp = retrieveDocumentResp;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://retailwebservicesv7.metcash.com")]
    public partial class listAllDocs
    {
        
        private string customerIdField;
        
        private string documentGUIDField;
        
        private string fileNameField;
        
        private string documentTypeField;
        
        private string hostTypeField;
        
        private DocumentReference[] documentReferenceField;
        
        private System.DateTime docDateField;
        
        private bool docDateFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string CustomerId
        {
            get
            {
                return this.customerIdField;
            }
            set
            {
                this.customerIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string DocumentGUID
        {
            get
            {
                return this.documentGUIDField;
            }
            set
            {
                this.documentGUIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string FileName
        {
            get
            {
                return this.fileNameField;
            }
            set
            {
                this.fileNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string DocumentType
        {
            get
            {
                return this.documentTypeField;
            }
            set
            {
                this.documentTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string HostType
        {
            get
            {
                return this.hostTypeField;
            }
            set
            {
                this.hostTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("DocumentReference", Order=5)]
        public DocumentReference[] DocumentReference
        {
            get
            {
                return this.documentReferenceField;
            }
            set
            {
                this.documentReferenceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public System.DateTime DocDate
        {
            get
            {
                return this.docDateField;
            }
            set
            {
                this.docDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DocDateSpecified
        {
            get
            {
                return this.docDateFieldSpecified;
            }
            set
            {
                this.docDateFieldSpecified = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class listDocumentsResponse
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://retailwebservicesv7.metcash.com")]
        public EDIServiceReference.Authentication Authentication;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://retailwebservicesv7.metcash.com", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("listAllDocs", IsNullable=false)]
        public EDIServiceReference.listAllDocs[] listDocumentsResp;
        
        public listDocumentsResponse()
        {
        }
        
        public listDocumentsResponse(EDIServiceReference.Authentication Authentication, EDIServiceReference.listAllDocs[] listDocumentsResp)
        {
            this.Authentication = Authentication;
            this.listDocumentsResp = listDocumentsResp;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://retailwebservicesv7.metcash.com")]
    public partial class getNextDocumentReq
    {
        
        private string customerIdField;
        
        private string stateCodeField;
        
        private string pillarIdField;
        
        private string documentTypeField;
        
        private string hostTypeField;
        
        private DocumentReference documentReferenceField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string CustomerId
        {
            get
            {
                return this.customerIdField;
            }
            set
            {
                this.customerIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string StateCode
        {
            get
            {
                return this.stateCodeField;
            }
            set
            {
                this.stateCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string PillarId
        {
            get
            {
                return this.pillarIdField;
            }
            set
            {
                this.pillarIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string DocumentType
        {
            get
            {
                return this.documentTypeField;
            }
            set
            {
                this.documentTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string HostType
        {
            get
            {
                return this.hostTypeField;
            }
            set
            {
                this.hostTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public DocumentReference DocumentReference
        {
            get
            {
                return this.documentReferenceField;
            }
            set
            {
                this.documentReferenceField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://retailwebservicesv7.metcash.com")]
    public partial class getNextDocumentResp
    {
        
        private string documentGUIDField;
        
        private string payloadField;
        
        private bool zipFlagField;
        
        private string documentVersionField;
        
        private string digestField;
        
        private string documentSizeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string DocumentGUID
        {
            get
            {
                return this.documentGUIDField;
            }
            set
            {
                this.documentGUIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Payload
        {
            get
            {
                return this.payloadField;
            }
            set
            {
                this.payloadField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public bool ZipFlag
        {
            get
            {
                return this.zipFlagField;
            }
            set
            {
                this.zipFlagField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string DocumentVersion
        {
            get
            {
                return this.documentVersionField;
            }
            set
            {
                this.documentVersionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Digest
        {
            get
            {
                return this.digestField;
            }
            set
            {
                this.digestField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string DocumentSize
        {
            get
            {
                return this.documentSizeField;
            }
            set
            {
                this.documentSizeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getNextDocumentRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://retailwebservicesv7.metcash.com")]
        public EDIServiceReference.OperatingSystem OperatingSystem;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://retailwebservicesv7.metcash.com")]
        public EDIServiceReference.VendorDetails VendorDetails;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://retailwebservicesv7.metcash.com")]
        public EDIServiceReference.Authentication Authentication;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://retailwebservicesv7.metcash.com", Order=0)]
        public EDIServiceReference.getNextDocumentReq getNextDocumentReq;
        
        public getNextDocumentRequest()
        {
        }
        
        public getNextDocumentRequest(EDIServiceReference.OperatingSystem OperatingSystem, EDIServiceReference.VendorDetails VendorDetails, EDIServiceReference.Authentication Authentication, EDIServiceReference.getNextDocumentReq getNextDocumentReq)
        {
            this.OperatingSystem = OperatingSystem;
            this.VendorDetails = VendorDetails;
            this.Authentication = Authentication;
            this.getNextDocumentReq = getNextDocumentReq;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getNextDocumentResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://retailwebservicesv7.metcash.com", Order=0)]
        public EDIServiceReference.getNextDocumentResp getNextDocumentResp;
        
        public getNextDocumentResponse()
        {
        }
        
        public getNextDocumentResponse(EDIServiceReference.getNextDocumentResp getNextDocumentResp)
        {
            this.getNextDocumentResp = getNextDocumentResp;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface RWSv7ServicesChannel : EDIServiceReference.RWSv7Services, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class RWSv7ServicesClient : System.ServiceModel.ClientBase<EDIServiceReference.RWSv7Services>, EDIServiceReference.RWSv7Services
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public RWSv7ServicesClient() : 
                base(RWSv7ServicesClient.GetDefaultBinding(), RWSv7ServicesClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.RWSv7ServicesEndpoint1.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public RWSv7ServicesClient(EndpointConfiguration endpointConfiguration) : 
                base(RWSv7ServicesClient.GetBindingForEndpoint(endpointConfiguration), RWSv7ServicesClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public RWSv7ServicesClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(RWSv7ServicesClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public RWSv7ServicesClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(RWSv7ServicesClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public RWSv7ServicesClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EDIServiceReference.listDocumentsInternalResponse> EDIServiceReference.RWSv7Services.listDocumentsInternalAsync(EDIServiceReference.listDocumentsInternalRequest request)
        {
            return base.Channel.listDocumentsInternalAsync(request);
        }
        
        public System.Threading.Tasks.Task<EDIServiceReference.listDocumentsInternalResponse> listDocumentsInternalAsync(EDIServiceReference.OperatingSystem OperatingSystem, EDIServiceReference.VendorDetails VendorDetails, EDIServiceReference.Authentication Authentication, EDIServiceReference.listDocumentsReq listDocumentsReq)
        {
            EDIServiceReference.listDocumentsInternalRequest inValue = new EDIServiceReference.listDocumentsInternalRequest();
            inValue.OperatingSystem = OperatingSystem;
            inValue.VendorDetails = VendorDetails;
            inValue.Authentication = Authentication;
            inValue.listDocumentsReq = listDocumentsReq;
            return ((EDIServiceReference.RWSv7Services)(this)).listDocumentsInternalAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EDIServiceReference.placeOrderResponse1> EDIServiceReference.RWSv7Services.placeOrderAsync(EDIServiceReference.placeOrderRequest1 request)
        {
            return base.Channel.placeOrderAsync(request);
        }
        
        public System.Threading.Tasks.Task<EDIServiceReference.placeOrderResponse1> placeOrderAsync(EDIServiceReference.OperatingSystem OperatingSystem, EDIServiceReference.VendorDetails VendorDetails, EDIServiceReference.Authentication Authentication, EDIServiceReference.placeOrderRequest placeOrderRequest)
        {
            EDIServiceReference.placeOrderRequest1 inValue = new EDIServiceReference.placeOrderRequest1();
            inValue.OperatingSystem = OperatingSystem;
            inValue.VendorDetails = VendorDetails;
            inValue.Authentication = Authentication;
            inValue.placeOrderRequest = placeOrderRequest;
            return ((EDIServiceReference.RWSv7Services)(this)).placeOrderAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EDIServiceReference.getOrderSummaryResponse1> EDIServiceReference.RWSv7Services.getOrderSummaryAsync(EDIServiceReference.getOrderSummaryRequest1 request)
        {
            return base.Channel.getOrderSummaryAsync(request);
        }
        
        public System.Threading.Tasks.Task<EDIServiceReference.getOrderSummaryResponse1> getOrderSummaryAsync(EDIServiceReference.OperatingSystem OperatingSystem, EDIServiceReference.VendorDetails VendorDetails, EDIServiceReference.Authentication Authentication, EDIServiceReference.getOrderSummaryRequest getOrderSummaryRequest)
        {
            EDIServiceReference.getOrderSummaryRequest1 inValue = new EDIServiceReference.getOrderSummaryRequest1();
            inValue.OperatingSystem = OperatingSystem;
            inValue.VendorDetails = VendorDetails;
            inValue.Authentication = Authentication;
            inValue.getOrderSummaryRequest = getOrderSummaryRequest;
            return ((EDIServiceReference.RWSv7Services)(this)).getOrderSummaryAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EDIServiceReference.retrieveDocumentResponse> EDIServiceReference.RWSv7Services.retrieveDocumentAsync(EDIServiceReference.retrieveDocumentRequest request)
        {
            return base.Channel.retrieveDocumentAsync(request);
        }
        
        public System.Threading.Tasks.Task<EDIServiceReference.retrieveDocumentResponse> retrieveDocumentAsync(EDIServiceReference.OperatingSystem OperatingSystem, EDIServiceReference.VendorDetails VendorDetails, EDIServiceReference.Authentication Authentication, EDIServiceReference.retrieveDocumentReq retrieveDocumentReq)
        {
            EDIServiceReference.retrieveDocumentRequest inValue = new EDIServiceReference.retrieveDocumentRequest();
            inValue.OperatingSystem = OperatingSystem;
            inValue.VendorDetails = VendorDetails;
            inValue.Authentication = Authentication;
            inValue.retrieveDocumentReq = retrieveDocumentReq;
            return ((EDIServiceReference.RWSv7Services)(this)).retrieveDocumentAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EDIServiceReference.listDocumentsResponse> EDIServiceReference.RWSv7Services.listDocumentsAsync(EDIServiceReference.listDocumentsInternalRequest request)
        {
            return base.Channel.listDocumentsAsync(request);
        }
        
        public System.Threading.Tasks.Task<EDIServiceReference.listDocumentsResponse> listDocumentsAsync(EDIServiceReference.OperatingSystem OperatingSystem, EDIServiceReference.VendorDetails VendorDetails, EDIServiceReference.Authentication Authentication, EDIServiceReference.listDocumentsReq listDocumentsReq)
        {
            EDIServiceReference.listDocumentsInternalRequest inValue = new EDIServiceReference.listDocumentsInternalRequest();
            inValue.OperatingSystem = OperatingSystem;
            inValue.VendorDetails = VendorDetails;
            inValue.Authentication = Authentication;
            inValue.listDocumentsReq = listDocumentsReq;
            return ((EDIServiceReference.RWSv7Services)(this)).listDocumentsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EDIServiceReference.getNextDocumentResponse> EDIServiceReference.RWSv7Services.getNextDocumentAsync(EDIServiceReference.getNextDocumentRequest request)
        {
            return base.Channel.getNextDocumentAsync(request);
        }
        
        public System.Threading.Tasks.Task<EDIServiceReference.getNextDocumentResponse> getNextDocumentAsync(EDIServiceReference.OperatingSystem OperatingSystem, EDIServiceReference.VendorDetails VendorDetails, EDIServiceReference.Authentication Authentication, EDIServiceReference.getNextDocumentReq getNextDocumentReq)
        {
            EDIServiceReference.getNextDocumentRequest inValue = new EDIServiceReference.getNextDocumentRequest();
            inValue.OperatingSystem = OperatingSystem;
            inValue.VendorDetails = VendorDetails;
            inValue.Authentication = Authentication;
            inValue.getNextDocumentReq = getNextDocumentReq;
            return ((EDIServiceReference.RWSv7Services)(this)).getNextDocumentAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.RWSv7ServicesEndpoint1))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.RWSv7ServicesEndpoint1))
            {
                return new System.ServiceModel.EndpointAddress("https://uatservices.metcash.com/api/retailServices/api/RetailWebServicesV7Service" +
                        "");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return RWSv7ServicesClient.GetBindingForEndpoint(EndpointConfiguration.RWSv7ServicesEndpoint1);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return RWSv7ServicesClient.GetEndpointAddress(EndpointConfiguration.RWSv7ServicesEndpoint1);
        }
        
        public enum EndpointConfiguration
        {
            
            RWSv7ServicesEndpoint1,
        }
    }
}
